### ISSUE TITLE
Adding Readme.md file 

### ISSUE THREAD

**Issue by bhati00** [vladpop20/moviestoreapp#1]
hello @vladpop20  can you please tell me , how to run this application , i dont have much experience with spring-boot. i want to contribute to this project.
i used the  mysql database to run this application. And can you please explain a bit more about this application.

**Comment by vladpop20** [comment]
Hello, firstly you need to have another microservice, just for Spring Cloud Eureka Server and Api Gateway. 
I will update this project, to also include those 2 microservices

**Comment by bhati00** [comment]
Thx @vladpop20 for replying, I'll also try to understand this project, and if i can do anything in this project , please open an issue for that.
